### ISSUE TITLE
Get DiffEqJump docs integrated

### ISSUE THREAD

**Issue by isaacsas** [SciML/SciMLDocs#1]
Since JumpProblem and such is not in SciMLBase or documented there.

**Comment by ChrisRackauckas** [comment]
Indeed. I think DiffEqJump needs an entire documentation: that page in DiffEq docs has gotten too crammed 😅 .

**Comment by isaacsas** [comment]
Yes, I've noticed that myself! It should be split into a series of tutorials. There is also more API type info that should be collated in a separate section, along with solver information and docs for the spatial stuff we have so far.
