### ISSUE TITLE
Buildkite-Based Documentation Deployments

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLDocs#106]
The following require it for either size or GPU requirements:

- [x] SciMLDocs (gpu)
- [x] DiffEqDocs
- [x] DiffEqGPU (gpu)
- [x] ReservoirComputing (gpu)
- [x] SciMLSensitivity (gpu)

Most don't exist with buildkite scripts yet, but those that do are having deployment issues.

Also, the buildkite scripts are not deploying on tags, so things like https://docs.sciml.ai/SciMLSensitivity/dev/ are missing a lot of tags.

**Comment by ArnoStrouwen** [comment]
DeepEquilibriumNetworks also? #107

**Comment by ChrisRackauckas** [comment]
Maybe. Does the docs use GPUs and big training? If so then yes.

**Comment by ChrisRackauckas** [comment]
All are set except the deployment issue. Once deployment is fixed, all 5 are done.
