### ISSUE TITLE
bayesian_neural_ode broken

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/SciMLDocs#142]
https://buildkite.com/julialang/scimldocs/builds/582#018665b2-60db-419d-af8e-cd3044293ce5/666-1133

**Comment by ChrisRackauckas** [comment]
The f function seems to be putting out values that are Float64 while the optimization is in Float32. That should get cleaned up.

**Comment by ArnoStrouwen** [comment]
Fixed by #144.
