### ISSUE TITLE
Error in example step 5:  GPU-Accelerated Physics-Informed Neural Network (PINN) PDE Solvers

### ISSUE THREAD

**Issue by andrewmcconnell** [SciML/SciMLDocs#143]
When stepping through the example code for GPU-Accelerated Physics-Informed Neural Network (PINN) PDE Solvers
at step 5, the line: 
prob = discretize(pde_system, discretization)

threw an error

ERROR: MethodError: no method matching CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}(::Matrix{Float64})

**Comment by ChrisRackauckas** [comment]
Ahh, somehow I missed that the builds were failing.

https://buildkite.com/julialang/scimldocs/builds/590#01866ad8-427d-42df-9800-3f63a0b52fd6

Yeah that just needs to keep Float32. Should be a simple fix.
