### ISSUE TITLE
edit on github button

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/SciMLDocs#15]
button does not work e.g. on:
https://docs.sciml.ai/dev/modules/LinearSolve/
https://github.com/SciML/SciMLDocs/blob/main/docs/src/modules/LinearSolve/index.md

**Comment by ChrisRackauckas** [comment]
Yeah, we'd need to figure out how to redirect them.

**Comment by ChrisRackauckas** [comment]
Apparently there is a solution: https://github.com/JuliaDocs/Documenter.jl/pull/700
