### ISSUE TITLE
Error in Getting Started tutorial

### ISSUE THREAD

**Issue by gustavdelius** [SciML/SciMLDocs#160]
In the tutorial "Solve your first optimization problem" at https://docs.sciml.ai/Overview/stable/getting_started/first_optimization/ we use a gradient-based method but do not supply the gradient. Thus instead of a solution `[NaN, NaN]` is returned, see https://docs.sciml.ai/Overview/stable/getting_started/first_optimization/#Step-3:-Solve-the-Optimization-Problem. The correct solution is of course `[1, 1]`.

We can either switch to a gradient-free method or we can use `Optimization.AutoForwardDiff()` as suggested in the example at https://docs.sciml.ai/Optimization/stable/getting_started/#Controlling-Gradient-Calculations-(Automatic-Differentiation)

**Comment by ChrisRackauckas** [comment]
Oops yes we should make it use Autodiff. I'm surprised that doesn't throw an error though (@Vaibhavdixit02)
