### ISSUE TITLE
NLopt failed to converge

### ISSUE THREAD

**Issue by xujc** [SciML/SciMLDocs#163]
When I run the exemplary code for "Solve your first optimization problem"

```
using Optimization, OptimizationNLopt

# Define the problem to optimize
L(u, p) = (p[1] - u[1])^2 + p[2] * (u[2] - u[1]^2)^2

# Define the Optimization Problem
u0 = zeros(2)
p = [1.0, 100.0]
prob = OptimizationProblem(L, u0, p, lb = -1 * ones(2), ub = ones(2))

# Solve the optimization problem
sol = solve(prob, NLopt.LD_LBFGS())
```
it gave a warning:
```
Warning: NLopt failed to converge: FORCED_STOP
└ @ OptimizationNLopt ~/.julia/packages/OptimizationNLopt/eAzgn/src/OptimizationNLopt.jl:231
```
and:
```
u: 2-element Vector{Float64}:
 NaN
 NaN
```
I guess the optimization was not successful?  
By the way, I am using Julia version 1.9.

**Comment by Vaibhavdixit02** [comment]
Were you looking at some other place than https://docs.sciml.ai/Optimization/stable/getting_started/? Btw you are missing defining an `OptimizationFunction` with an AD backend and using a derivative based optimizer BFGS. For reference https://docs.sciml.ai/Optimization/stable/getting_started/#Controlling-Gradient-Calculations-(Automatic-Differentiation)

**Comment by xujc** [comment]
@Vaibhavdixit02  Sorry, I forgot to give the link of the example code I mentioned ([Overview of Julia's SciML](https://docs.sciml.ai/Overview/stable/) - [Solve your first optimization problem](https://docs.sciml.ai/Overview/stable/getting_started/first_optimization/#first_opt)):
https://docs.sciml.ai/Overview/stable/getting_started/first_optimization/ . 

Indeed, it's not in the [Optimization](https://docs.sciml.ai/Optimization/stable/) section.

Thank you very much for your suggestion. I am a newbie and so I'll need to read the reference and figure out what you are talking about 😂.
