### ISSUE TITLE
Stable table of contents on docs

### ISSUE THREAD

**Issue by sophia-wright-blue** [SciML/SciMLDocs#165]
hello - this might seem like a trivial request, but it'd make navigating a lot easier:

when I click on a section in the scrollable Table of Contents, when the section comes up, the Table of Contents jumps back to the top and I have to scroll down to click on another section - it'd be great if the Table of Contents maintained its place even after the new section comes up

hope that makes sense - thank you!

**Comment by ChrisRackauckas** [comment]
I don't quite understand what you're saying. Can you maybe take a video to more clearly demonstrate what you mean? Maybe it's something that window-size specific?

**Comment by sophia-wright-blue** [comment]
I've attached a video - you can see that when I click on the section - SDE Problems, it jumps up to the top in the Table of Contents - I should repeat this might seem like a trivial request, so if you don't think it's inconvenient, please close the issue - thank you :)


https://github.com/SciML/SciMLDocs/assets/16384103/2c1e53a9-427d-4347-9097-f8db8b0d1346

**Comment by ChrisRackauckas** [comment]
Oh I see, this should be opened as an issue on Documenter.jl. It's a property of that documentation system.

https://github.com/JuliaDocs/Documenter.jl

**Comment by sophia-wright-blue** [comment]
thank you - I'll close the issue here and open it on the Documenter repo
