### ISSUE TITLE
Two competing showcases with @id autocomplete

### ISSUE THREAD

**Issue by gustavdelius** [SciML/SciMLDocs#181]
Since the new [black hole showcase](https://github.com/SciML/SciMLDocs/blob/9ae58af509d10eedc2a752b579be174d83ba3e1d/docs/src/showcase/blackhole.md) is using the same `@id autocomplete` as the old [Lotka-Volterra showcase](https://github.com/SciML/SciMLDocs/blob/9ae58af509d10eedc2a752b579be174d83ba3e1d/docs/src/showcase/missing_physics.md), the `@ref autocomplete` in the [showcases overview](https://github.com/SciML/SciMLDocs/blob/9ae58af509d10eedc2a752b579be174d83ba3e1d/docs/src/showcase/showcase.md?plain=1#L15) can not be resolved and the corresponding link is broken at https://docs.sciml.ai/Overview/stable/showcase/showcase/ .

**Comment by ChrisRackauckas** [comment]
Thanks! Fixed in the next build
