### ISSUE TITLE
Add more of the packages to the docs

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLDocs#2]
- [ ] SciMLParameters
- [x] DiffEqJump should be built from the DiffEqDocs pages
- [x] FEniCS 
- [x] HighDimPDE wait until https://github.com/SciML/HighDimPDE.jl/issues/30 https://github.com/SciML/HighDimPDE.jl/issues/26
- [x] NBodySimulator @SebastianM-C can you take this one?
- [ ] MinimallyDisruptiveCurves https://github.com/SciML/MinimallyDisruptiveCurves.jl/issues/14
- [x] StructuralIdentifiability @iliailmer this is having deps issues, maybe it needs https://github.com/SciML/StructuralIdentifiability.jl/pull/77 ?
- [x] DiffEqBayes @Vaibhavdixit02 can we get a version with less deps so it doesn't hold stuff back?
- [x] SymbolicNumericIntegration
- [x] DeepEquilibriumNetworks @avik-pal do you know what is holding versions back?
- [x] DiffEqUncertainty wait until https://github.com/SciML/DiffEqUncertainty.jl/pull/55
- [x] ReservoirComputing @MartinuzziFrancesco needs to change the GP to AbstractGPs.jl

**Comment by ChrisRackauckas** [comment]
@anandijain @paulflang  can you get something together for SBMLToolkit, ReactionNetworkImporters, and CellMLToolkit?

**Comment by iliailmer** [comment]
@ChrisRackauckas are there logs that I could look at to see what may be the issue? PR https://github.com/SciML/StructuralIdentifiability.jl/pull/77 shouldn't affect too much, except maybe latest julia versions (i.e. 1.8)?

**Comment by ArnoStrouwen** [comment]
Can this be updated?
DiffEqUncertainty has been done via SciMLExpectation?
I can't find SciMLParameters

**Comment by ChrisRackauckas** [comment]
> DiffEqUncertainty has been done via SciMLExpectation?

Yes

> I can't find SciMLParameters

Never made.

MinimallyDisruptiveCurves is really the last one here.

**Comment by ArnoStrouwen** [comment]
add https://github.com/SciML/DiffEqProblemLibrary.jl ?

**Comment by ChrisRackauckas** [comment]
The problem library is just integrated into the DiffEq documentation so I don't know if it needs to be standalone.

**Comment by ChrisRackauckas** [comment]
We can split this into specific requests now.
