### ISSUE TITLE
Broken hyperlink to showcase on front page

### ISSUE THREAD

**Issue by DanielVandH** [SciML/SciMLDocs#234]
On https://docs.sciml.ai/Overview/stable/, the hyperlink in the first point of the Reproducibility section is broken, showing

```
The documentation of the [SciML Showcase](@ref showcase) was built using these direct dependencies,
```

Not sure what the issue is, since https://github.com/SciML/SciMLDocs/blob/f5be870f44f744dbb429ea17dff67459d32c718c/docs/src/showcase/showcase.md?plain=1#L1 shows a valid matching `@id` and it's even correct in the Where to Start section on the same page. I'm guessing that wrapping it in ` ```@raw html` prevents the syntax from working.

**Comment by ChrisRackauckas** [comment]
@ArnoStrouwen

**Comment by ArnoStrouwen** [comment]
Yes, the reference can't be in raw html. Some variation of the following might work.
![image](https://github.com/SciML/SciMLDocs/assets/11204473/c8d95f26-88ca-4ccb-9f5a-d3ccdaaa1f58)
Will do a PR sometime next week if nobody got around to fixing it by then.
