### ISSUE TITLE
Standardize all repositories to the new and improved setup

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLDocs#24]
This includes:

- [x] Downstream testing gives code coverage https://github.com/SciML/ModelingToolkit.jl/pull/1656
- [x] All repos have the same badge setup, https://github.com/SciML/DiffEqSensitivity.jl/pull/651
- [x] All repos setup documentation code coverage https://github.com/SciML/DiffEqSensitivity.jl/pull/655
- [x] All repos set some strict modes on Documenter builds https://github.com/SciML/DiffEqSensitivity.jl/blob/v6.79.0/docs/make.jl#L16-L23
- [ ] All repos set tutorials to `@example` docs, like https://github.com/SciML/DiffEqSensitivity.jl/pull/649
- [x] Run the formatter on all repos
- [x] Add formatter to CI

Anything missed?

**Comment by isaacsas** [comment]
I don't know if having the download count is really needed or even wanted for all packages. Particularly for newer repos it will be quite low so not so great as an advertisement to use the package. 

Is there any reason you are dropping Coveralls from the badges? I usually find its coverage reports much more useful to go through interactively than codecov.

**Comment by MilkshakeForReal** [comment]
It seems like the current formatting CI will not format markdown files. Maybe we should add [format_md](https://domluna.github.io/JuliaFormatter.jl/dev/api/#JuliaFormatter.format_md-Tuple{AbstractString})? I could be wrong tho.

**Comment by MilkshakeForReal** [comment]
changing `format(".", verbose=true)` to `format(".", verbose=true, format_markdown=true)` would be good

**Comment by ChrisRackauckas** [comment]
Alright, the massive reorganization is starting to see the light at the end of the tunnel.

DiffEqJump -> JumpProcesses still needs to be done.

The formatter hit a lot of errors which were captured here: https://github.com/domluna/JuliaFormatter.jl/issues/610, so those repos will not have the formatter on them at least for now until that gets cleaned up.

Someone needs to go update the badges on all repos, 😅 that'll be fun.

Documentation coverage statistics increases the build times by more than 3x, which is not possible in some repos (like DiffEqSensitivity), but we should enable it where we can.

Strict mode for documenter is still necessary in a few repos, and that can happen in a case-by-case basis. NeuralPDE.jl is the next big one I'll be doing (and that may need to split parallelize those tests onto multiple CI to get below 3 hours), and then the DiffEqDocs. But there's a lot of other smaller ones that can probably be done in an hour or so (RecursiveArrayTools, LinearSolve, NonlinearSolve, Integrals, ...)

**Comment by ArnoStrouwen** [comment]
Most of the packages in the numerical utilities group just point toward a readme, because they don't have docs.
I think this should be standardized also.

**Comment by ChrisRackauckas** [comment]
I think the rest of the `@example`ing can be done on a repo-by-repo basis. I think it's just MTK and DiffEqDocs now.

Thanks all!
