### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLDocs#4]

**Comment by ChrisRackauckas** [comment]
![Screenshot 2022-06-04 092308](https://user-images.githubusercontent.com/1814174/172001045-b9e35b8d-0d40-41af-b606-95b81bb1194d.png)

**Comment by isaacsas** [comment]
```julia
rn = @reaction_network begin
              k, 🐑 + 🐺 --> 2*🐺
              k2, 🐺 --> ∅
              k3, 2🐑 --> 3*🐑
              end k k2 k3
```
apparently works in Catalyst too. Hah.

**Comment by ChrisRackauckas** [comment]
Life is Beautiful.

**Comment by ChrisRackauckas** [comment]
![SciML Map](https://user-images.githubusercontent.com/1814174/181920180-dfc6a920-d9ef-4813-bfc1-72726b6b2c56.png)
![SciML Map](https://user-images.githubusercontent.com/1814174/181920182-ea52f6c9-6afc-47f9-92dd-2b174513e3db.svg)
[SciML Map.pdf](https://github.com/SciML/SciMLDocs/files/9226720/SciML.Map.pdf)

**Comment by isaacsas** [comment]
That is fantastic!

**Comment by ChrisRackauckas** [comment]
![SciML Map Transparent](https://user-images.githubusercontent.com/1814174/182145762-6b91cff6-fa87-4021-b24a-fbc54ef98807.png)
![SciML Map](https://user-images.githubusercontent.com/1814174/182145763-79fce5ad-f1a0-4d4e-b417-1ac1894d391e.png)
[SciML Map.pdf](https://github.com/SciML/SciMLDocs/files/9233786/SciML.Map.pdf)
![SciML Map](https://user-images.githubusercontent.com/1814174/182145765-32b66b5a-1638-4aec-9d7e-74257b2c3f08.svg)

**Comment by ChrisRackauckas** [comment]
![Capture14](https://user-images.githubusercontent.com/1814174/195772770-e8f7b8f8-a853-4a95-a5c5-c6ed40f0c8d9.PNG)

**Comment by ChrisRackauckas** [comment]
![Capture15](https://user-images.githubusercontent.com/1814174/195773680-2226b2fc-5903-4eff-aae2-4d8689f16280.PNG)
![Capture16](https://user-images.githubusercontent.com/1814174/195773697-ede4edee-d479-46e8-acce-94a3ff884de8.PNG)

**Comment by ChrisRackauckas** [comment]
![Capture17](https://user-images.githubusercontent.com/1814174/195774460-9ea2e816-714d-4a43-9a52-82bc66fc3084.PNG)

**Comment by ChrisRackauckas** [comment]
![Capture17](https://user-images.githubusercontent.com/1814174/195774555-5841918e-e9a5-443c-9eca-84ed932af355.PNG)

**Comment by ChrisRackauckas** [comment]
![Capture18](https://user-images.githubusercontent.com/1814174/195775465-9e80de11-0b1e-4229-9eba-f5e49c9c81a1.PNG)

**Comment by ChrisRackauckas** [comment]
![Capture19](https://user-images.githubusercontent.com/1814174/195836404-ea69730e-69a4-4bf0-8d12-f57d5b8fce21.PNG)
