### ISSUE TITLE
Optimize S3 upload

### ISSUE THREAD

**Issue by staticfloat** [SciML/SciMLDocs#48]
We can optimize our S3 upload a bit by adding the following extra flags:

* `--size-only`: Only upload a version if the size of the object has changed.  Without this, since our timestamps are always newer (because we just copied all the files over) we're copying everything up every time.  Since the sizes of things should be changing when uploading, I think this is fairly safe to set.
* `--delete`: We want to remove files that no longer exist locally, so that when we delete a file, it gets deleted on S3 as well.

Also, we can split the `Aggregate.yml` file into two pieces, on that does the build, one that does the upload, so that only the upload part is signed.  This will allow `Aggregate.yml` to be an unsigned pipeline, and editable without needing @thazhemadam to re-sign the pipelines.  :)

**Comment by thazhemadam** [comment]
> Also, we can split the Aggregate.yml file into two pieces, on that does the build, one that does the upload, so that only the upload part is signed.

Doesn't the build part also need to be signed since we encrypt the `DOCUMENTER_KEY`?

**Comment by thazhemadam** [comment]
On second thought, we might need to consolidate both steps into one because buildkite's artifacts have an upload size limit of 5GB, which our documentation builds easily surpass, so we can't have them in separate steps. Closing this issue.
