### ISSUE TITLE
Documenter @example blocks not being executed

### ISSUE THREAD

**Issue by isaacsas** [SciML/SciMLDocs#5]
A bunch of the Catalyst docs have dynamic output using `@example` blocks, but these seem like they aren't being executed here. See https://docs.sciml.ai/dev/modules/Catalyst/tutorials/symbolic_stoich/ and compare to https://catalyst.sciml.ai/dev/tutorials/symbolic_stoich/

**Comment by isaacsas** [comment]
Seems like the Project.toml needs to add packages that the Catalyst examples depend on, or the docs need a way to pull in the Project.tomls from each sub-documentation set.

**Comment by isaacsas** [comment]
https://github.com/SciML/SciMLDocs/runs/6744526705?check_suite_focus=true#step:5:21

**Comment by ChrisRackauckas** [comment]
The problem is that the `modlist` is only filled with libraries used as sublibraries right now. The one exception is Plots.jl:

https://github.com/SciML/SciMLDocs/blob/main/docs/make.jl#L123

We should instead have a whole list of extra modules, such as Latexify.jl, at all get `using`'d and `push!`ed to the module list. That would then solve this issue (which is asking for Latexify.jl to be defined, but I'm sure there are many other cases throughout the docs that will need to be appropriately handled).

**Comment by isaacsas** [comment]
Is that the recommended way to include other libraries that are not part of the documentation but need to get loaded? In Catalyst we just add them to the Project.toml, but not the module list. Documenter says 

"modules specifies a vector of modules that should be documented in source. If any inline docstrings from those modules are seen to be missing from the generated content then a warning will be printed during execution of [makedocs](https://juliadocs.github.io/Documenter.jl/dev/lib/public/#Documenter.makedocs). By default no modules are passed to modules and so no warnings will appear. This setting can be used as an indicator of the "coverage" of the generated documentation. For example Documenter's make.jl file contains:"

so it doesn't seem like that is the intended use of the `modules` kwarg. (And pulling them in will give lots of warnings in the build process I think.)

**Comment by ChrisRackauckas** [comment]
We at least need to add Latexify to the Project.toml and do `using` for it, and yes the modules list is only for the libraries which you wish to grab docstrings from.

**Comment by isaacsas** [comment]
I’ll try updating the Project.toml locally and checking it fixes the issues, and then submit a PR.

**Comment by isaacsas** [comment]
https://github.com/SciML/SciMLDocs/pull/7 seems to fix the Catalyst doc build locally for me.
