### ISSUE TITLE
Make docs.sciml.ai the default for all of SciML

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLDocs#53]
Now that this is starting to deploy, we need to update everything to be pointing here. For every package, we need:

- Update the docs badges to just have a badge pointing to the docs.sciml.ai version
- Update the build canonical links to point there https://github.com/SciML/DiffEqFlux.jl/blob/master/docs/make.jl#L25
- Add redirects to the new site pages (I'm not quite sure how)
- Update the within-package and between-package links to these new pages (to try and avoid the redirects)
- Update the Github repo settings so the canonical website link is to the global package docs.

@ArnoStrouwen can you help with this?

**Comment by ArnoStrouwen** [comment]
Yes, I'm going to a conference this week so these menial tasks like updating badges are a good fit.

**Comment by ArnoStrouwen** [comment]
Should DifferentialEquations also just get fully merged into SciMLDocs, or do you want to keep a standalone version there?

**Comment by ChrisRackauckas** [comment]
We should keep a separate version for that for both formatting reasons (so it shows up in the top bar), and because we intend to make all of its tutorials into `@examples` so it'll be a big build process of its own.

**Comment by ArnoStrouwen** [comment]
Not yet done:
- DiffEqDocs
- SciMLBase
- SciMLTutorials
- SciMLBenchmarks

**Comment by ChrisRackauckas** [comment]
And the redirects, though the redirects could be their own issue.

**Comment by ArnoStrouwen** [comment]
I can't do much about the redirects without access to sciml.ai
My guess is it could be done using
https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-page-redirect.html. 
removing any CNAME records already there and also removing the github pages custom domains in each repo's settings?

**Comment by ChrisRackauckas** [comment]
I did a test redirect with noise.sciml.ai awhile ago and that worked. So now I setup the rest and in a day or so the DNS update should resolve and this should be done.

**Comment by ChrisRackauckas** [comment]
Done
