### ISSUE TITLE
Some packages have embedded links to old sciml documentation  

### ISSUE THREAD

**Issue by 00krishna** [SciML/SciMLDocs#68]
As we update the documentation links across SciML packages, most packages only have old links in the README and `make.jl` files. However, some older packages have a lot of links to the old documentation link format in their source files. This issue notes the relevant packages so that we can resolve them later. 

- [ ] SciMLBase
- [ ] DiffEqFlux
- [ ] DeepEquilibriumNetworks
- [ ] SciMLExpectations

**Comment by ChrisRackauckas** [comment]
@ArnoStrouwen got all of these?

**Comment by ArnoStrouwen** [comment]
I think 90% of in between SciML links are updated, at least for most repos.
Some of the big repos, like DiffEqDocs, still need to be done.
I also did not test if every single outside link still went where it is supposed to go.

**Comment by ChrisRackauckas** [comment]
Alright, that's enough to close and make it more specific as we spot things.

**Comment by 00krishna** [comment]
Yeah sounds good. I was kinda waiting till the first pass was complete, to make sure things worked. If everyone thinks it is cool, I can start to go through and change the inner links now. I think that the majority of them were in SciMLBase.
