### ISSUE TITLE
Missing logos in some packages

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLDocs#70]
- [ ] PoissonRandom
- [ ] CellMLToolkit
- [ ] SciMLExpectations
- [ ] ModelOrderReduction
- [ ] MuladdMacro
- [ ] CellMLToolkit

**Comment by ArnoStrouwen** [comment]
Can't figure out HighDimPDE, it seems to have the assets but no logo shown?
https://github.com/ArnoStrouwen/HighDimPDE.jl/tree/main/docs/src/assets
https://github.com/ArnoStrouwen/HighDimPDE.jl/blob/539ca5e77a76e14222239baeaea001f9a7f964a2/docs/make.jl#L16

https://docs.sciml.ai/HighDimPDE/stable/

**Comment by ChrisRackauckas** [comment]
It's in the dev build https://docs.sciml.ai/HighDimPDE/dev/ just needs a tag.

**Comment by ArnoStrouwen** [comment]
I think I got them all.
