### ISSUE TITLE
Flux.jl adds `.jl` to the folder name for some reason in the top bar

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLDocs#71]
@pfitzseb is there any explanation for this one? Seems like a an odd thing that is happening on its own.

**Comment by pfitzseb** [comment]
https://github.com/FluxML/Flux.jl/blob/gh-pages/index.html forces a redirect to /Flux.jl/stable.

**Comment by ChrisRackauckas** [comment]
Awesome, I opened an upstream https://github.com/FluxML/Flux.jl/pull/2093
