### ISSUE TITLE
Trimming down DiffEqDocs

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/SciMLDocs#78]
Now that we have SciMLDocs, some of the pages of DiffEqDocs are no longer relevant.

- [x] Move (still actively maintained) external modeling tools to top bar https://diffeq.sciml.ai/latest/models/external_modeling/
- [x] Catalyst already in SciMLDocs https://diffeq.sciml.ai/latest/models/chemical_reactions/
- [x] idem NBodySimulator https://diffeq.sciml.ai/latest/models/physical/
- [x] idem MultiScaleArrays https://diffeq.sciml.ai/latest/models/multiscale/
- [x] DiffEqFinancial did not get the unified docs treatment yet https://diffeq.sciml.ai/latest/models/financial/

Replace the above with a single overview page mentioning them all?

Analysis Tools

- [x] Trim all of them

**Comment by ChrisRackauckas** [comment]
Yeah that can all be trimmed out.
