### ISSUE TITLE
Non https link to the devdocs in the diffeq docs

### ISSUE THREAD

**Issue by gbaraldi** [SciML/SciMLDocs#85]
https://diffeq.sciml.ai/stable/analysis/dev_and_test/ The link in this page redirects to an http link instead of the https one, which leads to the not secure badge in chrome

**Comment by ChrisRackauckas** [comment]
That's already removed on dev.

**Comment by 00krishna** [comment]
Additional resolution with 
https://github.com/SciML/DiffEqDocs.jl/pull/598
